sonar.projectKey=Polliog_BugBoard26
sonar.organization=polliog
sonar.sourceEncoding=UTF-8
sonar.java.source=23

# Source paths
sonar.sources=progetto/api/src/main/java
sonar.tests=progetto/api/src/test/java
sonar.java.binaries=progetto/api/target/classes
sonar.java.test.binaries=progetto/api/target/test-classes

# Exclusions
sonar.exclusions=**/node_modules/**,progetto/web/build/**,progetto/web/.svelte-kit/**

# Coverage (JaCoCo)
sonar.coverage.jacoco.xmlReportPaths=progetto/api/target/site/jacoco/jacoco.xml
