sonar.projectKey=Polliog_BugBoard26
sonar.organization=polliog
sonar.sourceEncoding=UTF-8
sonar.java.source=23

# Source paths
sonar.sources=api/src/main/java
sonar.tests=api/src/test/java
sonar.java.binaries=api/target/classes
sonar.java.test.binaries=api/target/test-classes

# Exclusions
sonar.exclusions=**/node_modules/**,web/build/**,web/.svelte-kit/**

# Coverage (JaCoCo)
sonar.coverage.jacoco.xmlReportPaths=api/target/site/jacoco/jacoco.xml
